### ISSUE TITLE
Embedded YouTube not starting at beginning

### ISSUE THREAD

**Issue by jeffzira** [mahadana/pujas.live#27]
day 5 chanting starts at 57 minutes. Not right. Jeff to handle. Anapanasati also not working, maybe not embeddable

**Comment by vjagaro** [comment]
It looks like this issue is due to a few factors:

- One must be signed into YouTube (Google)
- One must have enabled (or not disabled) YouTube video watch history

When the both of the above factors are present, YouTube videos, whether watched on YouTube or via embed, will behave differently when the video was previously watched:

- The video will not autoplay (the wrapper we're using overrides this)
- The video will start at the last playing time
